$ROOT     = Split-Path -Parent $MyInvocation.MyCommand.Path
$ENV_FILE = Join-Path $ROOT "backend\.env"
$NGROK    = "$env:TEMP\ngrok.exe"

Write-Host ""
Write-Host "=== Incomiq ngrok Static Domain Setup ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Open this URL in your browser:" -ForegroundColor Yellow
Write-Host "  https://dashboard.ngrok.com/cloud-edge/domains" -ForegroundColor White
Write-Host "  Click '+ New Domain' — you'll get a free permanent domain" -ForegroundColor Gray
Write-Host ""

$domain = Read-Host "Paste your static domain (e.g. sparkling-fox.ngrok-free.app)"
$domain = $domain.Trim() -replace "^https?://", ""

if (-not $domain) { Write-Host "ERROR: No domain provided." -ForegroundColor Red; exit 1 }

$tunnelUrl = "https://$domain"

# Save config
@"
# Auto-generated by setup-ngrok.ps1
NGROK_DOMAIN=$domain
NGROK_EXE=$NGROK
"@ | Set-Content (Join-Path $ROOT ".ngrok-config")

# Update .env
if (Test-Path $ENV_FILE) {
    $c = Get-Content $ENV_FILE -Raw
    $c = $c -replace "APP_BASE_URL=.*", "APP_BASE_URL=$tunnelUrl"
    Set-Content $ENV_FILE $c -NoNewline
}

Write-Host ""
Write-Host "Done! Permanent webhook URL:" -ForegroundColor Green
Write-Host "  $tunnelUrl/api/sms/webhook" -ForegroundColor Cyan
Write-Host ""
Write-Host "Update httpSMS app to this URL — you'll NEVER need to change it again." -ForegroundColor Yellow
Write-Host "Then run: .\tunnel-keepalive.ps1" -ForegroundColor White
Write-Host ""
# Run this ONCE to configure ngrok with your permanent static domain.
# After this, tunnel-keepalive.ps1 will always use the same URL.
#
# Steps:
#   1. Sign up free at https://ngrok.com
#   2. Go to https://dashboard.ngrok.com/get-started/your-authtoken
#      Copy your authtoken
#   3. Go to https://dashboard.ngrok.com/cloud-edge/domains
#      Click "Create Domain" (free static domain, e.g. lucky-cat-entirely.ngrok-free.app)
#   4. Run this script and paste both values when prompted

$ROOT     = Split-Path -Parent $MyInvocation.MyCommand.Path
$ENV_FILE = Join-Path $ROOT "backend\.env"
$NGROK    = Join-Path $env:TEMP "ngrok.exe"
$CFG_FILE = Join-Path $ROOT "ngrok.yml"

Write-Host ""
Write-Host "=== Incomiq ngrok Setup ===" -ForegroundColor Cyan
Write-Host ""

# ── Download ngrok ─────────────────────────────────────────
if (-not (Test-Path $NGROK)) {
    Write-Host "Downloading ngrok..." -ForegroundColor Yellow
    $zipPath = Join-Path $env:TEMP "ngrok.zip"
    Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" `
        -OutFile $zipPath -UseBasicParsing
    Expand-Archive -Path $zipPath -DestinationPath $env:TEMP -Force
    Remove-Item $zipPath -Force
    Write-Host "ngrok downloaded." -ForegroundColor Green
} else {
    Write-Host "ngrok already downloaded." -ForegroundColor Green
}

# ── Collect inputs ─────────────────────────────────────────
Write-Host ""
Write-Host "Open these links:" -ForegroundColor Yellow
Write-Host "  Authtoken : https://dashboard.ngrok.com/get-started/your-authtoken" -ForegroundColor White
Write-Host "  Domain    : https://dashboard.ngrok.com/cloud-edge/domains  (click Create Domain)" -ForegroundColor White
Write-Host ""

$token  = Read-Host "Paste your ngrok Authtoken"
$domain = Read-Host "Paste your static domain (e.g. lucky-cat-entirely.ngrok-free.app)"

if (-not $token -or -not $domain) {
    Write-Host "ERROR: Both authtoken and domain are required." -ForegroundColor Red
    exit 1
}

# Strip protocol if user pasted full URL
$domain = $domain -replace "^https?://",""

# ── Configure ngrok ────────────────────────────────────────
& $NGROK config add-authtoken $token 2>&1 | Out-Null

# Write local config for this project
@"
version: "3"
agent:
  authtoken: $token
tunnels:
  incomiq:
    proto: http
    addr: 8000
    domain: $domain
"@ | Set-Content $CFG_FILE

Write-Host ""
Write-Host "ngrok configured!" -ForegroundColor Green

# ── Update .env ────────────────────────────────────────────
$tunnelUrl = "https://$domain"
if (Test-Path $ENV_FILE) {
    $env_content = Get-Content $ENV_FILE -Raw
    if ($env_content -match "APP_BASE_URL=") {
        $env_content = $env_content -replace "APP_BASE_URL=.*", "APP_BASE_URL=$tunnelUrl"
    } else {
        $env_content = $env_content.TrimEnd() + "`nAPP_BASE_URL=$tunnelUrl`n"
    }
    Set-Content $ENV_FILE $env_content -NoNewline
    Write-Host "Updated backend/.env with permanent URL." -ForegroundColor Green
}

# ── Save domain for keepalive script ──────────────────────
@"
# Auto-generated by setup-ngrok.ps1 — DO NOT EDIT MANUALLY
NGROK_DOMAIN=$domain
NGROK_EXE=$NGROK
"@ | Set-Content (Join-Path $ROOT ".ngrok-config")

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  PERMANENT Webhook URL:" -ForegroundColor White
Write-Host "  $tunnelUrl/api/sms/webhook" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Update httpSMS app webhook URL to:" -ForegroundColor White
Write-Host "     $tunnelUrl/api/sms/webhook" -ForegroundColor Green
Write-Host "  2. Run tunnel-keepalive.ps1 instead of start-sms-tunnel.ps1" -ForegroundColor White
Write-Host "     This URL will NEVER change again." -ForegroundColor Cyan
Write-Host ""
